### ISSUE TITLE
Need to fix some templates as they are not working

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/gorjun#213]
1. Wordpress - has connection refused error
2. Zookeeper - when you ssh it, container is open, but it doesn't allow to enter container
3. P2Pcollect - failed to get tunnels
4. Mongo - builds for more than half an hour
5. Elasticsearch -failed to get tunnels

**Comment by emli** [comment]
1) Old wordpress template deleted because it didn't work, you can use new [one ](https://mastercdn.subut.ai:8338/kurjun/rest/template/list?id=c1bbe775-58fe-439d-a5f0-4b61e822ddb0)
2) I tested `Zookeeper` template on prod , because it's same template, I was able ssh to container
Other issues are not related not gorjun directly.

**Comment by amol4anoff** [comment]
Wordpress - deleted;
Zookeeper - ok
P2pcollect - ok
Mongo - ok
Elasticsearch - ok

**Comment by amol4anoff** [comment]
@emli fixed.
