### ISSUE TITLE
REST endpoint for file searching is needed

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/gorjun#70]
We need to be able to search files by their name in Kurjun. Searching should find files by any occurrence of search string in file name, with ignoring letter case.

Also may be would be useful to make search endpoint to accept filtering parameters.
Kurjun already has filter by `owner` field, following fields also candidates for filtering:
- in templates:
1. architecture
2. parent template
3. version
- in raw files:
1. version

**Comment by tzununbekov** [comment]
Info endpoint in dev now checks not only name prefix but works with `if contains` logic: https://devcdn.subut.ai:8338/kurjun/rest/raw/info?name=do_it
This might create additional load on gorjun's database, but in  current implementation there is not much options to go. 
Additional filtering issue might be postponed since there is no practical need in this feature right now whereas implementation might take a significant effort
